apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: devops
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels: { app: mongo }
  template:
    metadata: { labels: { app: mongo } }
    spec:
      containers:
      - name: mongo
        image: mongo:7
        ports: [ { containerPort: 27017 } ]
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom: { secretKeyRef: { name: mongo-secret, key: MONGO_INITDB_ROOT_USERNAME } }
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom: { secretKeyRef: { name: mongo-secret, key: MONGO_INITDB_ROOT_PASSWORD } }
        volumeMounts:
        - name: mongo-vol
          mountPath: /data/db
      volumes:
      - name: mongo-vol
        persistentVolumeClaim:
          claimName: mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: devops
spec:
  selector: { app: mongo }
  ports: [ { port: 27017, targetPort: 27017 } ]
